"""Agent core components."""

from me.agent.core import Agent, AgentConfig
from me.agent.body import (
    BodyDirectory,
    AgentIdentity,
    AgentConfig as BodyConfig,
    Embodiment,
    Mood,
    SomaticMode,
    Character,
    WorkingSet,
    MouthConfig,
    MouthMode,
    SensorsConfig,
    SensorDefinition,
    Focus,
    Episode,
    Procedure,
    SignificantMoment,
    Intention,
    Theory,
)
from me.agent.unconscious import (
    UnconsciousDirectory,
    UnconsciousRunner,
    Pipeline,
    PipelineTrigger,
    PipelineSource,
    TriggerMode,
    # Daemon system (Agentic OS)
    Daemon,
    DaemonState,
    Runlevel,
    ProcessGroup,
    TokenBudget,
    JournalEntry,
    LogLevel,
    # Semantic routing
    DaemonProfile,
    cosine_similarity,
    # Daemon Graph Templates (Higher-Order Abstraction)
    DaemonGraphTemplate,
    RewardSource,
    MetaDaemon,
    MetaDaemonCapability,
    # Default installations
    install_default_pipelines,
    install_default_templates,
    install_default_reward_sources,
    install_extended_groups,
    DEFAULT_TEMPLATES,
    DEFAULT_REWARD_SOURCES,
    EXTENDED_GROUPS,
)
from me.agent.memory import Memory
from me.agent.mcp import MCPRegistry
from me.agent.process import ProcessReader

# Learning and metacognition
from me.agent.learning import (
    ExperienceBuffer,
    Experience,
    ExperienceType,
    PredictionTracker,
    Prediction,
    ProcedureUpdater,
    ProcedureStats,
    PatternExtractor,
    Pattern,
    TheoryRefiner,
    Evidence,
    ExperienceReplay,
)
from me.agent.skills import (
    Skill,
    SkillMetadata,
    SkillType,
    SkillState,
    SkillIndex,
    SkillManager,
    SkillComposer,
    SkillSystem,
)
from me.agent.skill_integration import (
    SkillRecommender,
    SkillRecommendation,
    SkillExtractor,
    SkillCandidate,
    SkillDaemonManager,
    SkillCharacterMapping,
    SkillDependencyResolver,
    AtrophyDetector,
    AtrophyWarning,
    SkillTransfer,
    SkillPackage,
    SkillIntegration,
    compute_skill_embedding,
    update_skill_embeddings,
    semantic_skill_search,
    apply_skill_character_evolution,
)
from me.agent.skill_mcp import (
    SkillMCPHandler,
    SKILL_TOOLS,
)
from me.agent.evolution import (
    PerformanceArea,
    PerformanceInsight,
    PerformanceReport,
    SelfAnalyzer,
    GoalType,
    IntrinsicGoal,
    CuriosityEngine,
    ErrorPattern,
    ErrorRecoveryLearner,
    CharacterEvolutionEvent,
    CharacterEvolver,
    Experiment,
    ExperimentRunner,
    EvolutionSystem,
)
from me.agent.autonomy import (
    AutonomyLevel,
    ActionRisk,
    AutonomyPolicy,
    ActionRequest,
    ActionDecision,
    AutonomyManager,
    ConfirmationRequest,
    ConfirmationQueue,
    classify_action_risk,
)
from me.agent.metacognition import (
    PerformanceMonitor,
    PerformanceSnapshot,
    CognitiveMetric,
    StuckDetector,
    StuckDetection,
    StuckType,
    StrategyTracker,
    Strategy,
    AdaptationEngine,
    Adaptation,
    NoveltyDetector,
    MetaCognitiveMonitor,
)

# World model and causality
from me.agent.world_model import (
    FileSystemModel,
    FileNode,
    FileType,
    ProcessModel,
    ProcessNode,
    TransitionModel,
    StateTransition,
    WorldModel,
)
from me.agent.causality import (
    CausalGraph,
    CausalEdge,
    CausalRelationType,
    CausalObservation,
    CausalDiscovery,
    CounterfactualReasoner,
    Counterfactual,
    InterventionPlanner,
    Intervention,
    CausalReasoner,
)
from me.agent.communication import (
    Message,
    MessageType,
    MessagePriority,
    Channel,
    AgentInfo,
    AgentDirectory,
    SharedBlackboard,
    AgentBus,
)
from me.agent.planning import (
    Goal,
    GoalStatus,
    GoalPriority,
    GoalGraph,
    Plan,
    PlanStep,
    PlanStatus,
    Planner,
    PlanningStrategy,
    PlanEvaluator,
    StrategicReasoner,
    StrategicInsight,
    StrategicPlanningSystem,
)

# Deep learning and behavioral improvement
from me.agent.deep_learning import (
    Strategy as LearningStrategy,
    StrategyOutcome,
    StrategyApplication,
    StrategyLibrary,
    PromptTemplate,
    PromptRefinementEngine,
    ActionSequence,
    SequenceDetector,
    Feedback,
    CreditAssigner,
    ABTest,
    ABTestRunner,
    DeepLearningSystem,
)

# Tool synthesis
from me.agent.tool_synthesis import (
    ToolType,
    ToolStatus,
    ToolParameter,
    ToolTestCase,
    ToolTestResult,
    SynthesizedTool,
    PatternToToolSpec,
    ToolSynthesizer,
    ToolValidator,
    ToolDeployer,
    ToolSynthesisSystem,
)

# Memory consolidation
from me.agent.consolidation import (
    ConsolidationPhase,
    MemoryValue,
    Schema,
    PruneDecision,
    ConsolidationReport,
    MemoryValuator,
    EpisodeCompressor,
    MemoryPruner,
    PatternAbstractor,
    ConsolidationEngine,
    ConsolidationDaemon,
    MemoryConsolidationSystem,
)

# Strategic reasoning
from me.agent.strategic import (
    ResourceType,
    StrategicHorizon,
    ResourceBudget,
    ResourceState,
    StrategicGoal,
    OpportunityCost,
    StrategicOption,
    StrategicDecision,
    ResourceTracker,
    GoalManager,
    OptionEvaluator,
    StrategicPlanner,
    DecisionLogger,
    StrategicReasoningSystem,
)

# Self-model
from me.agent.self_model import (
    CapabilityDomain,
    ConfidenceLevel,
    FailureMode,
    CapabilityProfile,
    FailurePrediction,
    CalibrationMetric,
    CompetenceTrajectory,
    LimitationAcknowledgment,
    TaskFeasibility,
    CapabilityTracker,
    FailurePredictor,
    ConfidenceCalibrator,
    CompetenceMonitor,
    LimitationRegistry,
    FeasibilityAssessor,
    SelfModelSystem,
)

__all__ = [
    # Core
    "Agent",
    "AgentConfig",
    # Body
    "BodyDirectory",
    "AgentIdentity",
    "BodyConfig",
    "Embodiment",
    "Mood",
    "SomaticMode",
    "Character",
    "WorkingSet",
    "MouthConfig",
    "MouthMode",
    "SensorsConfig",
    "SensorDefinition",
    # Memory types
    "Episode",
    "Procedure",
    "SignificantMoment",
    "Intention",
    "Theory",
    # Unconscious
    "UnconsciousDirectory",
    "UnconsciousRunner",
    "Pipeline",
    "PipelineTrigger",
    "PipelineSource",
    "TriggerMode",
    "Focus",
    # Daemon system (Agentic OS)
    "Daemon",
    "DaemonState",
    "Runlevel",
    "ProcessGroup",
    "TokenBudget",
    "JournalEntry",
    "LogLevel",
    # Semantic routing
    "DaemonProfile",
    "cosine_similarity",
    # Daemon Graph Templates (Higher-Order Abstraction)
    "DaemonGraphTemplate",
    "RewardSource",
    "MetaDaemon",
    "MetaDaemonCapability",
    # Default installations
    "install_default_pipelines",
    "install_default_templates",
    "install_default_reward_sources",
    "install_extended_groups",
    "DEFAULT_TEMPLATES",
    "DEFAULT_REWARD_SOURCES",
    "EXTENDED_GROUPS",
    # Other components
    "Memory",
    "MCPRegistry",
    "ProcessReader",
    # Learning
    "ExperienceBuffer",
    "Experience",
    "ExperienceType",
    "PredictionTracker",
    "Prediction",
    "ProcedureUpdater",
    "ProcedureStats",
    "PatternExtractor",
    "Pattern",
    "TheoryRefiner",
    "Evidence",
    "ExperienceReplay",
    # Skills
    "Skill",
    "SkillMetadata",
    "SkillType",
    "SkillState",
    "SkillIndex",
    "SkillManager",
    "SkillComposer",
    "SkillSystem",
    # Skill Integration
    "SkillRecommender",
    "SkillRecommendation",
    "SkillExtractor",
    "SkillCandidate",
    "SkillDaemonManager",
    "SkillCharacterMapping",
    "SkillDependencyResolver",
    "AtrophyDetector",
    "AtrophyWarning",
    "SkillTransfer",
    "SkillPackage",
    "SkillIntegration",
    "compute_skill_embedding",
    "update_skill_embeddings",
    "semantic_skill_search",
    "apply_skill_character_evolution",
    # Skill MCP
    "SkillMCPHandler",
    "SKILL_TOOLS",
    # Evolution
    "PerformanceArea",
    "PerformanceInsight",
    "PerformanceReport",
    "SelfAnalyzer",
    "GoalType",
    "IntrinsicGoal",
    "CuriosityEngine",
    "ErrorPattern",
    "ErrorRecoveryLearner",
    "CharacterEvolutionEvent",
    "CharacterEvolver",
    "Experiment",
    "ExperimentRunner",
    "EvolutionSystem",
    # Autonomy
    "AutonomyLevel",
    "ActionRisk",
    "AutonomyPolicy",
    "ActionRequest",
    "ActionDecision",
    "AutonomyManager",
    "ConfirmationRequest",
    "ConfirmationQueue",
    "classify_action_risk",
    # Metacognition
    "PerformanceMonitor",
    "PerformanceSnapshot",
    "CognitiveMetric",
    "StuckDetector",
    "StuckDetection",
    "StuckType",
    "StrategyTracker",
    "Strategy",
    "AdaptationEngine",
    "Adaptation",
    "NoveltyDetector",
    "MetaCognitiveMonitor",
    # World Model
    "FileSystemModel",
    "FileNode",
    "FileType",
    "ProcessModel",
    "ProcessNode",
    "TransitionModel",
    "StateTransition",
    "WorldModel",
    # Causality
    "CausalGraph",
    "CausalEdge",
    "CausalRelationType",
    "CausalObservation",
    "CausalDiscovery",
    "CounterfactualReasoner",
    "Counterfactual",
    "InterventionPlanner",
    "Intervention",
    "CausalReasoner",
    # Communication
    "Message",
    "MessageType",
    "MessagePriority",
    "Channel",
    "AgentInfo",
    "AgentDirectory",
    "SharedBlackboard",
    "AgentBus",
    # Planning
    "Goal",
    "GoalStatus",
    "GoalPriority",
    "GoalGraph",
    "Plan",
    "PlanStep",
    "PlanStatus",
    "Planner",
    "PlanningStrategy",
    "PlanEvaluator",
    "StrategicReasoner",
    "StrategicInsight",
    "StrategicPlanningSystem",
    # Deep Learning
    "LearningStrategy",
    "StrategyOutcome",
    "StrategyApplication",
    "StrategyLibrary",
    "PromptTemplate",
    "PromptRefinementEngine",
    "ActionSequence",
    "SequenceDetector",
    "Feedback",
    "CreditAssigner",
    "ABTest",
    "ABTestRunner",
    "DeepLearningSystem",
    # Tool Synthesis
    "ToolType",
    "ToolStatus",
    "ToolParameter",
    "ToolTestCase",
    "ToolTestResult",
    "SynthesizedTool",
    "PatternToToolSpec",
    "ToolSynthesizer",
    "ToolValidator",
    "ToolDeployer",
    "ToolSynthesisSystem",
    # Memory Consolidation
    "ConsolidationPhase",
    "MemoryValue",
    "Schema",
    "PruneDecision",
    "ConsolidationReport",
    "MemoryValuator",
    "EpisodeCompressor",
    "MemoryPruner",
    "PatternAbstractor",
    "ConsolidationEngine",
    "ConsolidationDaemon",
    "MemoryConsolidationSystem",
    # Strategic Reasoning
    "ResourceType",
    "StrategicHorizon",
    "ResourceBudget",
    "ResourceState",
    "StrategicGoal",
    "OpportunityCost",
    "StrategicOption",
    "StrategicDecision",
    "ResourceTracker",
    "GoalManager",
    "OptionEvaluator",
    "StrategicPlanner",
    "DecisionLogger",
    "StrategicReasoningSystem",
    # Self-Model
    "CapabilityDomain",
    "ConfidenceLevel",
    "FailureMode",
    "CapabilityProfile",
    "FailurePrediction",
    "CalibrationMetric",
    "CompetenceTrajectory",
    "LimitationAcknowledgment",
    "TaskFeasibility",
    "CapabilityTracker",
    "FailurePredictor",
    "ConfidenceCalibrator",
    "CompetenceMonitor",
    "LimitationRegistry",
    "FeasibilityAssessor",
    "SelfModelSystem",
]
